// 50+ Realistic E-Commerce Products across Categories & Brands for KuKu Kart (INR Pricing)

export const CATEGORIES_DATA = [
  { id: 'cat-1', name: 'Men', slug: 'men', image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600&q=80', count: 12 },
  { id: 'cat-2', name: 'Women', slug: 'women', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80', count: 12 },
  { id: 'cat-3', name: 'Electronics', slug: 'electronics', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', count: 10 },
  { id: 'cat-4', name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', count: 10 },
  { id: 'cat-5', name: 'Footwear', slug: 'footwear', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', count: 8 },
  { id: 'cat-6', name: 'Beauty', slug: 'beauty', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80', count: 8 },
  { id: 'cat-7', name: 'Home & Living', slug: 'home-living', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80', count: 8 },
  { id: 'cat-8', name: 'Kids', slug: 'kids', image: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?w=600&q=80', count: 6 },
  { id: 'cat-9', name: 'Grocery', slug: 'grocery', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80', count: 6 }
];

export const BRANDS_DATA = [
  'KuKu Atelier', 'Obsidian Luxe', 'Aura Soundworks', 'Velvet & Silk', 
  'Titanium Edge', 'Maison Royale', 'Apex Performance', 'Sovereign Home', 
  'Elysian Tailors', 'Little Monarch', 'Pure Organics'
];

export const PRODUCTS_MASTER = [
  // MEN (1-8)
  {
    id: 'm1',
    title: 'Imperial Cashmere Overcoat',
    subtitle: '100% Pure Mongolian Cashmere Tailored Coat',
    brand: 'Elysian Tailors',
    category: 'Men',
    price: 8999,
    originalPrice: 12999,
    discountPercent: 31,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1544022613-e87ce7526edb?w=800&q=80',
    stock: 14,
    sizes: ['38R', '40R', '42R', '44R'],
    colors: ['Charcoal Grey', 'Midnight Black', 'Camel Tan'],
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    description: 'Mastercrafted from double-faced pure Mongolian cashmere with hand-stitched horn buttons and satin lining.'
  },
  {
    id: 'm2',
    title: 'Savile Row Velvet Tuxedo Jacket',
    subtitle: 'Deep Obsidian Velvet Evening Jacket',
    brand: 'KuKu Atelier',
    category: 'Men',
    price: 14999,
    originalPrice: 19999,
    discountPercent: 25,
    rating: 5.0,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
    stock: 8,
    sizes: ['38', '40', '42', '44'],
    colors: ['Obsidian Black', 'Midnight Blue', 'Emerald Green'],
    isFeatured: true,
    isDealOfTheDay: true,
    isBestSeller: true,
    description: 'Flawless formal tailoring with satin peak lapels and structured shoulder line. Ideal for galas and royal celebrations.'
  },
  {
    id: 'm3',
    title: 'Pima Cotton Mercerized Polo',
    subtitle: 'High-twist breathable luxury polo shirt',
    brand: 'Elysian Tailors',
    category: 'Men',
    price: 1999,
    originalPrice: 2999,
    discountPercent: 33,
    rating: 4.7,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1625910513413-56254a61352a?w=800&q=80',
    stock: 45,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy Blue', 'Snow White', 'Olive Gold'],
    isBestSeller: true,
    description: 'Silky smooth feel with mother-of-pearl buttons and shape-retaining ribbed collar.'
  },
  {
    id: 'm4',
    title: 'Tailored Merino Wool Trousers',
    subtitle: 'Pleated drape with side waist adjusters',
    brand: 'Elysian Tailors',
    category: 'Men',
    price: 3499,
    originalPrice: 4999,
    discountPercent: 30,
    rating: 4.8,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
    stock: 22,
    sizes: ['30', '32', '34', '36', '38'],
    colors: ['Slate Grey', 'Espresso Brown', 'Classic Navy'],
    description: 'Super 150s merino wool with natural stretch and wrinkle resistance. Hand-finished hems.'
  },
  {
    id: 'm5',
    title: 'Royal Linen Bandhgala Kurta Set',
    subtitle: 'Hand-loomed Pure Irish Linen Ceremonial Attire',
    brand: 'KuKu Atelier',
    category: 'Men',
    price: 6999,
    originalPrice: 9999,
    discountPercent: 30,
    rating: 4.9,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=800&q=80',
    stock: 15,
    sizes: ['38', '40', '42', '44'],
    colors: ['Ivory Gold', 'Midnight Navy'],
    isNewArrival: true,
    description: 'Crisp hand-woven pure linen kurta with tailored churidar trousers and engraved gold metal buttons.'
  },

  // WOMEN (6-11)
  {
    id: 'w1',
    title: 'Aura Silk Chiffon Evening Gown',
    subtitle: 'Floor-length flowing haute couture silhouette',
    brand: 'Velvet & Silk',
    category: 'Women',
    price: 18999,
    originalPrice: 24999,
    discountPercent: 24,
    rating: 5.0,
    reviewsCount: 204,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80',
    stock: 6,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Scarlet Red', 'Emerald Silk', 'Noir Black'],
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    description: 'Hand-draped pure mulberry silk chiffon with subtle corseted bodice and flowing hemline.'
  },
  {
    id: 'w2',
    title: 'Cashmere Ribbed Knit Cardigan',
    subtitle: 'Oversized luxury knitwear with tortoise buttons',
    brand: 'Velvet & Silk',
    category: 'Women',
    price: 4999,
    originalPrice: 6999,
    discountPercent: 29,
    rating: 4.8,
    reviewsCount: 168,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
    stock: 18,
    sizes: ['S', 'M', 'L'],
    colors: ['Alabaster Cream', 'Camel', 'Mocha'],
    isDealOfTheDay: true,
    isTrending: true,
    description: 'Heavyweight ribbed grade-A cashmere knit with soft drop shoulders and natural mother-of-pearl buttons.'
  },
  {
    id: 'w3',
    title: 'Structured Double-Breasted Blazer',
    subtitle: 'Sculpted hourglass silhouette power blazer',
    brand: 'KuKu Atelier',
    category: 'Women',
    price: 7999,
    originalPrice: 10999,
    discountPercent: 27,
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    stock: 12,
    sizes: ['34', '36', '38', '40'],
    colors: ['Onyx Black', 'Ivory White', 'Crimson Red'],
    isNewArrival: true,
    description: 'Impeccable shoulder pads, cinched waist, and gold bullion buttons. Italian wool blend.'
  },
  {
    id: 'w4',
    title: 'Banarasi Kanjeevaram Silk Saree',
    subtitle: 'Pure zari hand-woven heirloom drape',
    brand: 'Velvet & Silk',
    category: 'Women',
    price: 15999,
    originalPrice: 21999,
    discountPercent: 27,
    rating: 5.0,
    reviewsCount: 154,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80',
    stock: 9,
    sizes: ['Free Size (6.3m with blouse)'],
    colors: ['Royal Magenta & Gold', 'Emerald Green & Gold'],
    isFeatured: true,
    isBestSeller: true,
    description: 'Pure mulberry silk woven with authentic gold tested zari by master artisans in Varanasi.'
  },

  // ELECTRONICS (12-16)
  {
    id: 'e1',
    title: 'Aura Studio Wireless Headphones',
    subtitle: 'Bespoke Titanium & Lambskin Acoustics',
    brand: 'Aura Soundworks',
    category: 'Electronics',
    price: 6499,
    originalPrice: 9999,
    discountPercent: 35,
    rating: 4.9,
    reviewsCount: 420,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    stock: 25,
    sizes: ['Standard Edition', 'Pro Reference'],
    colors: ['Matte Black', 'Brushed Titanium', 'Champagne Gold'],
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    description: 'Custom 50mm planar magnetic drivers delivering pristine audiophile fidelity with active noise isolation.'
  },
  {
    id: 'e2',
    title: 'Obsidian 16 Pro Flagship Laptop',
    subtitle: 'Liquid-cooled OLED Creator Workstation',
    brand: 'Titanium Edge',
    category: 'Electronics',
    price: 84999,
    originalPrice: 99999,
    discountPercent: 15,
    rating: 5.0,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
    stock: 9,
    sizes: ['32GB RAM / 1TB SSD', '64GB RAM / 2TB SSD'],
    colors: ['Space Obsidian', 'Liquid Silver'],
    isFeatured: true,
    isNewArrival: true,
    description: 'Precision CNC-machined aerospace aluminum unibody with 4K OLED ProMotion 120Hz display.'
  },
  {
    id: 'e3',
    title: 'Stealth Tactile Mechanical Keyboard',
    subtitle: 'Forged carbon fiber wireless keyboard',
    brand: 'Titanium Edge',
    category: 'Electronics',
    price: 3499,
    originalPrice: 4999,
    discountPercent: 30,
    rating: 4.8,
    reviewsCount: 185,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
    stock: 30,
    sizes: ['75% Compact', '100% Full Size'],
    colors: ['Obsidian Black', 'Cyber Grey'],
    isDealOfTheDay: true,
    description: 'Hot-swappable custom lubricated linear switches with brass weight bar and per-key RGB backlighting.'
  },
  {
    id: 'e4',
    title: 'Audiophile Tube Amplifier & DAC',
    subtitle: 'Hand-wired pure Class-A tube amplification',
    brand: 'Aura Soundworks',
    category: 'Electronics',
    price: 18499,
    originalPrice: 22999,
    discountPercent: 20,
    rating: 4.9,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
    stock: 7,
    sizes: ['Desktop DAC', 'High-Output Pro'],
    colors: ['Brushed Copper', 'Matte Black'],
    description: 'Analog warmth meets ultra-high resolution 32-bit/768kHz digital decoding with matched vacuum tubes.'
  },

  // ACCESSORIES & HOROLOGY (17-21)
  {
    id: 'a1',
    title: 'The Sovereign Chronograph',
    subtitle: 'Hand-assembled Tourbillon Timepiece',
    brand: 'KuKu Atelier',
    category: 'Accessories',
    price: 24999,
    originalPrice: 32999,
    discountPercent: 24,
    rating: 5.0,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    stock: 5,
    sizes: ['40mm Case', '42mm Case'],
    colors: ['Rose Gold / Alligator Strap', 'Platinum / Steel Bracelet'],
    isFeatured: true,
    isDealOfTheDay: true,
    isBestSeller: true,
    description: 'Certified automatic chronometer with 72-hour power reserve, sapphire crystal back, and water resistance to 100m.'
  },
  {
    id: 'a2',
    title: 'Titanium Aviator Sunglasses',
    subtitle: 'Polarized 24k Gold Flake Japanese Lenses',
    brand: 'Titanium Edge',
    category: 'Accessories',
    price: 3999,
    originalPrice: 5999,
    discountPercent: 33,
    rating: 4.8,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
    stock: 24,
    sizes: ['Standard 58mm', 'Large 62mm'],
    colors: ['Gold / Green Gradient', 'Gunmetal / Smoke'],
    isTrending: true,
    description: 'Ultralight Japanese titanium frame weighing under 16 grams with 100% UV400 antireflective coating.'
  },
  {
    id: 'a3',
    title: 'Full-Grain Leather Duffle Bag',
    subtitle: 'Tuscan vegetable-tanned handcrafted weekender',
    brand: 'KuKu Atelier',
    category: 'Accessories',
    price: 6999,
    originalPrice: 9999,
    discountPercent: 30,
    rating: 4.9,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    stock: 11,
    sizes: ['45L Weekend', '60L Extended'],
    colors: ['Cognac Brown', 'Midnight Noir'],
    isNewArrival: true,
    description: 'Solid brass hardware with custom initials tag, reinforced bottom studs, and waterproof lining.'
  },

  // FOOTWEAR (22-24)
  {
    id: 'f1',
    title: 'Verona Calfskin Oxford Shoes',
    subtitle: 'Goodyear-welted Italian Dress Shoes',
    brand: 'Apex Performance',
    category: 'Footwear',
    price: 5999,
    originalPrice: 8499,
    discountPercent: 29,
    rating: 4.9,
    reviewsCount: 132,
    image: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80',
    stock: 16,
    sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
    colors: ['Hand-burnished Tan', 'Deep Black'],
    isTrending: true,
    isBestSeller: true,
    description: 'Full-grain French calfskin with hand-stained leather soles and channel welted stitching for lifetime resoling.'
  },
  {
    id: 'f2',
    title: 'Carbon-Fiber Runner Sneaker',
    subtitle: 'Propulsion plate ultra-cushioning runners',
    brand: 'Apex Performance',
    category: 'Footwear',
    price: 3299,
    originalPrice: 4999,
    discountPercent: 34,
    rating: 4.8,
    reviewsCount: 290,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    stock: 35,
    sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
    colors: ['Crimson Stealth', 'Triple Black', 'Polar White'],
    isFeatured: true,
    isDealOfTheDay: true,
    description: 'Supercritical PEBA foam midsole with curved carbon plate delivering maximum energy return on city streets.'
  },

  // BEAUTY & WELLNESS (25-27)
  {
    id: 'b1',
    title: 'Oud Royale Extrait de Parfum',
    subtitle: 'Rare Cambodian Oud & Damask Rose Niche Perfume',
    brand: 'Maison Royale',
    category: 'Beauty',
    price: 4999,
    originalPrice: 6999,
    discountPercent: 29,
    rating: 5.0,
    reviewsCount: 175,
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
    stock: 20,
    sizes: ['50ml Extrait', '100ml Extrait'],
    colors: ['Crystal Flacon'],
    isFeatured: true,
    isDealOfTheDay: true,
    description: '35% pure fragrance oil concentration aged for 18 months in French oak casks.'
  },
  {
    id: 'b2',
    title: 'Botanical Cellular Restorative Serum',
    subtitle: 'Swiss Alpine Stem Cell Formulation',
    brand: 'Maison Royale',
    category: 'Beauty',
    price: 2499,
    originalPrice: 3499,
    discountPercent: 29,
    rating: 4.8,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
    stock: 28,
    sizes: ['30ml Pipette', '50ml Pump'],
    colors: ['Amber Glass'],
    isNewArrival: true,
    description: 'Deep cellular rejuvenation with plant hyaluronic acid and peptide complex for luminous hydration.'
  },

  // HOME & LIVING (28-30)
  {
    id: 'h1',
    title: 'Carrara Marble & Brass Table Lamp',
    subtitle: 'Sculptural architectural ambient lighting',
    brand: 'Sovereign Home',
    category: 'Home & Living',
    price: 5499,
    originalPrice: 7999,
    discountPercent: 31,
    rating: 4.9,
    reviewsCount: 56,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    stock: 8,
    sizes: ['Medium 45cm', 'Large 60cm'],
    colors: ['Honed Carrara / Brushed Brass'],
    isFeatured: true,
    description: 'Solid Italian Carrara marble base with dimmable warm LED filament and braided fabric cord.'
  },
  {
    id: 'h2',
    title: 'Mulberry Silk 1000TC Bedding Set',
    subtitle: 'King Suite 6-piece temperature-regulating luxury linens',
    brand: 'Sovereign Home',
    category: 'Home & Living',
    price: 8999,
    originalPrice: 12999,
    discountPercent: 31,
    rating: 5.0,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    stock: 12,
    sizes: ['Queen Bedding', 'King Master Bedding'],
    colors: ['Champagne Pearl', 'Slate Charcoal', 'Pure Ivory'],
    isBestSeller: true,
    description: 'Organic long-strand Grade 6A mulberry silk with hypoallergenic finish and deep envelope pillowcases.'
  },

  // GROCERY & GOURMET (31-33)
  {
    id: 'g1',
    title: 'Single-Estate Himalayan Organic Green Tea',
    subtitle: 'First Flush Darjeeling artisanal loose leaves',
    brand: 'Pure Organics',
    category: 'Grocery',
    price: 999,
    originalPrice: 1499,
    discountPercent: 33,
    rating: 4.9,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&q=80',
    stock: 50,
    sizes: ['250g Tin', '500g Pouch'],
    colors: ['Airtight Gold Canister'],
    isTrending: true,
    isDealOfTheDay: true,
    description: 'Hand-plucked high-altitude whole leaves rich in natural antioxidants with delicate muscatel floral notes.'
  },
  {
    id: 'g2',
    title: 'Kashmiri Mogra Saffron (Grade A1)',
    subtitle: '100% Pure certified vacuum-sealed saffron filaments',
    brand: 'Pure Organics',
    category: 'Grocery',
    price: 1499,
    originalPrice: 1999,
    discountPercent: 25,
    rating: 5.0,
    reviewsCount: 312,
    image: 'https://images.unsplash.com/photo-1608686207856-001b95cf60ca?w=800&q=80',
    stock: 40,
    sizes: ['2g Premium Jar', '5g Gift Box'],
    colors: ['Sealed Acrylic Box'],
    isBestSeller: true,
    description: 'Highest crocin content harvested directly from the valleys of Pampore, Kashmir.'
  },
  {
    id: 'g3',
    title: 'Artisanal Cold-Pressed Extra Virgin Olive Oil',
    subtitle: 'Single-estate early harvest unfiltered olive oil',
    brand: 'Pure Organics',
    category: 'Grocery',
    price: 1299,
    originalPrice: 1799,
    discountPercent: 28,
    rating: 4.8,
    reviewsCount: 160,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
    stock: 35,
    sizes: ['500ml Dark Glass', '1000ml Tin'],
    colors: ['Dark UV-Protected Bottle'],
    description: 'Sub-0.2% acidity with robust peppery finish. Pressed within 4 hours of tree harvesting.'
  }
];
