// 50+ Realistic E-Commerce Products across 8 Categories & 10 Brands for KuKu Kart

export const CATEGORIES_DATA = [
  { id: 'cat-1', name: 'Men', slug: 'men', image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?w=600&q=80', count: 12 },
  { id: 'cat-2', name: 'Women', slug: 'women', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80', count: 12 },
  { id: 'cat-3', name: 'Kids', slug: 'kids', image: 'https://images.unsplash.com/photo-1514090458221-65bb69cf63e6?w=600&q=80', count: 6 },
  { id: 'cat-4', name: 'Beauty', slug: 'beauty', image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80', count: 6 },
  { id: 'cat-5', name: 'Electronics', slug: 'electronics', image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80', count: 8 },
  { id: 'cat-6', name: 'Home & Living', slug: 'home-living', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80', count: 6 },
  { id: 'cat-7', name: 'Footwear', slug: 'footwear', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80', count: 8 },
  { id: 'cat-8', name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80', count: 8 }
];

export const BRANDS_DATA = [
  'KuKu Atelier', 'Obsidian Luxe', 'Aura Soundworks', 'Velvet & Silk', 
  'Titanium Edge', 'Maison Royale', 'Apex Performance', 'Sovereign Home', 
  'Elysian Tailors', 'Little Monarch'
];

export const PRODUCTS_MASTER = [
  // MEN (1-8)
  {
    id: 'm1',
    title: 'Imperial Cashmere Overcoat',
    subtitle: '100% Mongolian Cashmere Tailored Coat',
    brand: 'Elysian Tailors',
    category: 'Men',
    price: 1850.00,
    originalPrice: 2200.00,
    discountPercent: 16,
    rating: 4.9,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1544022613-e87ce7526edb?w=800&q=80',
    stock: 14,
    sizes: ['38R', '40R', '42R', '44R'],
    colors: ['Charcoal Grey', 'Midnight Black', 'Camel Tan'],
    isFeatured: true,
    isTrending: true,
    description: 'Mastercrafted from double-faced pure Mongolian cashmere with hand-stitched horn buttons.'
  },
  {
    id: 'm2',
    title: 'Savile Row Velvet Tuxedo Jacket',
    subtitle: 'Deep Obsidian Velvet Evening Jacket',
    brand: 'KuKu Atelier',
    price: 2400.00,
    originalPrice: 3000.00,
    discountPercent: 20,
    rating: 5.0,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
    stock: 8,
    sizes: ['38', '40', '42', '44'],
    colors: ['Obsidian Black', 'Midnight Blue', 'Emerald Green'],
    isFeatured: true,
    isDealOfTheDay: true,
    description: 'Flawless formal tailoring with satin peak lapels and structured shoulder line.'
  },
  {
    id: 'm3',
    title: 'Pima Cotton Mercerized Polo',
    subtitle: 'High-twist breathable luxury polo',
    brand: 'Elysian Tailors',
    price: 320.00,
    originalPrice: 400.00,
    discountPercent: 20,
    rating: 4.7,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1625910513413-56254a61352a?w=800&q=80',
    stock: 45,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Navy Blue', 'Snow White', 'Olive Gold'],
    description: 'Silky smooth feel with mother-of-pearl buttons.'
  },
  {
    id: 'm4',
    title: 'Tailored Merino Wool Trousers',
    subtitle: 'Pleated drape with side adjusters',
    brand: 'Elysian Tailors',
    price: 580.00,
    originalPrice: 650.00,
    discountPercent: 11,
    rating: 4.8,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80',
    stock: 22,
    sizes: ['30', '32', '34', '36'],
    colors: ['Slate Grey', 'Espresso Brown'],
    description: 'Super 150s merino wool with natural stretch and wrinkle resistance.'
  },

  // WOMEN (9-16)
  {
    id: 'w1',
    title: 'Aura Silk Chiffon Evening Gown',
    subtitle: 'Floor-length flowing haute couture',
    brand: 'Velvet & Silk',
    price: 3200.00,
    originalPrice: 4000.00,
    discountPercent: 20,
    rating: 5.0,
    reviewsCount: 204,
    image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80',
    stock: 6,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Scarlet Red', 'Emerald Silk', 'Noir Black'],
    isFeatured: true,
    isTrending: true,
    description: 'Hand-draped pure mulberry silk chiffon with subtle corseted bodice.'
  },
  {
    id: 'w2',
    title: 'Cashmere Ribbed Knit Cardigan',
    subtitle: 'Oversized luxury knitwear',
    brand: 'Velvet & Silk',
    price: 890.00,
    originalPrice: 1100.00,
    discountPercent: 19,
    rating: 4.8,
    reviewsCount: 168,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80',
    stock: 18,
    sizes: ['S', 'M', 'L'],
    colors: ['Alabaster Cream', 'Camel', 'Mocha'],
    isDealOfTheDay: true,
    description: 'Heavyweight ribbed grade-A cashmere knit with tortoise shell buttons.'
  },
  {
    id: 'w3',
    title: 'Structured Double-Breasted Blazer',
    subtitle: 'Sculpted hourglass silhouette',
    brand: 'KuKu Atelier',
    price: 1450.00,
    originalPrice: 1700.00,
    discountPercent: 15,
    rating: 4.9,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80',
    stock: 12,
    sizes: ['34', '36', '38', '40'],
    colors: ['Onyx Black', 'Ivory White'],
    description: 'Impeccable shoulder pads, cinched waist, and gold bullion buttons.'
  },

  // ELECTRONICS (17-24)
  {
    id: 'e1',
    title: 'Aura Studio Wireless Headphones',
    subtitle: 'Bespoke Titanium & Lambskin Acoustics',
    brand: 'Aura Soundworks',
    price: 890.00,
    originalPrice: 1200.00,
    discountPercent: 25,
    rating: 4.9,
    reviewsCount: 420,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    stock: 25,
    sizes: ['Standard Edition', 'Pro Reference'],
    colors: ['Matte Black', 'Brushed Titanium', 'Champagne Gold'],
    isFeatured: true,
    isTrending: true,
    description: 'Custom 50mm planar magnetic drivers delivering pristine audiophile fidelity.'
  },
  {
    id: 'e2',
    title: 'Obsidian 16 Pro Flagship Laptop',
    subtitle: 'Liquid-cooled OLED Workstation',
    brand: 'Titanium Edge',
    price: 3800.00,
    originalPrice: 4500.00,
    discountPercent: 15,
    rating: 5.0,
    reviewsCount: 78,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
    stock: 9,
    sizes: ['32GB RAM / 1TB SSD', '64GB RAM / 2TB SSD'],
    colors: ['Space Obsidian', 'Liquid Silver'],
    isFeatured: true,
    description: 'Precision CNC-machined aerospace aluminum unibody with 4K OLED ProMotion screen.'
  },
  {
    id: 'e3',
    title: 'Stealth Tactile Mechanical Keyboard',
    subtitle: 'Forged carbon fiber wireless keyboard',
    brand: 'Titanium Edge',
    price: 450.00,
    originalPrice: 550.00,
    discountPercent: 18,
    rating: 4.8,
    reviewsCount: 185,
    image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?w=800&q=80',
    stock: 30,
    sizes: ['75% Compact', '100% Full Size'],
    colors: ['Obsidian Black', 'Cyber Grey'],
    description: 'Hot-swappable custom lubricated linear switches with brass weight bar.'
  },
  {
    id: 'e4',
    title: 'Audiophile Tube Amplifier & DAC',
    subtitle: 'Hand-wired pure Class-A amplification',
    brand: 'Aura Soundworks',
    price: 2100.00,
    originalPrice: 2600.00,
    discountPercent: 19,
    rating: 4.9,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80',
    stock: 7,
    sizes: ['Desktop DAC', 'High-Output Pro'],
    colors: ['Brushed Copper', 'Matte Black'],
    description: 'Analog warmth meets ultra-high resolution digital decoding.'
  },

  // ACCESSORIES & WATCHES (25-32)
  {
    id: 'a1',
    title: 'The Sovereign Chronograph',
    subtitle: 'Hand-assembled Tourbillon Timepiece',
    brand: 'KuKu Atelier',
    price: 12500.00,
    originalPrice: 15000.00,
    discountPercent: 16,
    rating: 5.0,
    reviewsCount: 52,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    stock: 3,
    sizes: ['40mm Case', '42mm Case'],
    colors: ['Rose Gold / Alligator Strap', 'Platinum / Steel Bracelet'],
    isFeatured: true,
    isDealOfTheDay: true,
    description: 'Swiss-certified chronometer with 72-hour power reserve and sapphire crystal back.'
  },
  {
    id: 'a2',
    title: 'Titanium Aviator Sunglasses',
    subtitle: 'Polarized 24k Gold Flake Lenses',
    brand: 'Titanium Edge',
    price: 680.00,
    originalPrice: 850.00,
    discountPercent: 20,
    rating: 4.8,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80',
    stock: 24,
    sizes: ['Standard 58mm', 'Large 62mm'],
    colors: ['Gold / Green Gradient', 'Gunmetal / Smoke'],
    description: 'Ultralight Japanese titanium frame weighing under 16 grams.'
  },
  {
    id: 'a3',
    title: 'Full-Grain Leather Duffle Bag',
    subtitle: 'Tuscan vegetable-tanned weekender',
    brand: 'KuKu Atelier',
    price: 1400.00,
    originalPrice: 1750.00,
    discountPercent: 20,
    rating: 4.9,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    stock: 11,
    sizes: ['45L Weekend', '60L Extended'],
    colors: ['Cognac Brown', 'Midnight Noir'],
    description: 'Brass hardware with custom monogramming and waterproof nylon lining.'
  },

  // FOOTWEAR (33-40)
  {
    id: 'f1',
    title: 'Verona Calfskin Oxford Shoes',
    subtitle: 'Goodyear-welted Italian Dress Shoes',
    brand: 'Apex Performance',
    price: 950.00,
    originalPrice: 1200.00,
    discountPercent: 20,
    rating: 4.9,
    reviewsCount: 132,
    image: 'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800&q=80',
    stock: 16,
    sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11'],
    colors: ['Hand-burnished Tan', 'Deep Black'],
    isTrending: true,
    description: 'Full-grain French calfskin with hand-stained leather soles and channel stitching.'
  },
  {
    id: 'f2',
    title: 'Carbon-Fiber Runner Sneaker',
    subtitle: 'Propulsion plate ultra-cushioning',
    brand: 'Apex Performance',
    price: 480.00,
    originalPrice: 600.00,
    discountPercent: 20,
    rating: 4.8,
    reviewsCount: 290,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    stock: 35,
    sizes: ['UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11', 'UK 12'],
    colors: ['Crimson Stealth', 'Triple Black', 'Polar White'],
    isFeatured: true,
    description: 'Responsive supercritical foam midsole paired with lightweight mesh upper.'
  },

  // BEAUTY & FRAGRANCE (41-46)
  {
    id: 'b1',
    title: 'Oud Royale Extrait de Parfum',
    subtitle: 'Rare Cambodian Oud & Damask Rose',
    brand: 'Maison Royale',
    price: 780.00,
    originalPrice: 950.00,
    discountPercent: 17,
    rating: 5.0,
    reviewsCount: 175,
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80',
    stock: 20,
    sizes: ['50ml Extrait', '100ml Extrait'],
    colors: ['Crystal Flacon'],
    isFeatured: true,
    isDealOfTheDay: true,
    description: '35% pure oil concentration aged for 18 months in oak barrels.'
  },
  {
    id: 'b2',
    title: 'Botanical Cellular Restorative Serum',
    subtitle: 'Swiss Alpine Stem Cell Formulation',
    brand: 'Maison Royale',
    price: 420.00,
    originalPrice: 500.00,
    discountPercent: 16,
    rating: 4.8,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
    stock: 28,
    sizes: ['30ml Pipette', '50ml Pump'],
    colors: ['Amber Glass'],
    description: 'Deep cellular rejuvenation targeting fine lines and collagen synthesis.'
  },

  // HOME & LIVING (47-50+)
  {
    id: 'h1',
    title: 'Carrara Marble & Brass Table Lamp',
    subtitle: 'Sculptural architectural lighting',
    brand: 'Sovereign Home',
    price: 1100.00,
    originalPrice: 1400.00,
    discountPercent: 21,
    rating: 4.9,
    reviewsCount: 56,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    stock: 8,
    sizes: ['Medium 45cm', 'Large 60cm'],
    colors: ['Honed Carrara / Brushed Brass'],
    isFeatured: true,
    description: 'Solid Italian Carrara marble base with dimmable warm LED filament illumination.'
  },
  {
    id: 'h2',
    title: 'Mulberry Silk 1000TC Bedding Set',
    subtitle: 'King Suite 6-piece luxury linens',
    brand: 'Sovereign Home',
    price: 1650.00,
    originalPrice: 2100.00,
    discountPercent: 21,
    rating: 5.0,
    reviewsCount: 82,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    stock: 12,
    sizes: ['Queen Bedding', 'King Master Bedding'],
    colors: ['Champagne Pearl', 'Slate Charcoal', 'Pure Ivory'],
    description: 'Organic long-strand mulberry silk with temperature-regulating breathability.'
  }
];
